version: '3'
services:
  centos-web:
    container_name: centos-web
    image: centos-web:latest
    build: ./docker/web
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    links:
      - centos-db:db

  centos-db:
    container_name: centos-db
    image: centos-db:latest
    build: ./docker/db
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
