version: '3'
services:
  centos-app:
    container_name: centos-app
    image: centos-app:latest
    build: ./docker/app
    ports:
      - 443:443
    volumes:
      - ./:/var/www
    links:
      - centos-db:db

  # centos-cms:
  #   container_name: centos-cms
  #   image: centos-cms:latest
  #   build: ./docker/cms
  #   ports:
  #     - 10443:443
  #   volumes:
  #     - ./:/var/www
  #   links:
  #     - centos-db:db

  centos-db:
    container_name: centos-db
    image: centos-db:latest
    build: ./docker/db
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
