version: '3'
services:
  nginx:
    container_name: phalcon-nginx
    image: phalcon-nginx:latest
    build: ./docker/nginx
    ports:
      - 8080:80
    links:
      - app:app

  app:
    container_name: phalcon-app
    image: phalcon-app:latest
    build: ./docker/app
    volumes:
      - ./:/var/www
    links:
      - db:db

  db:
    container_name: phalcon-db
    image: phalcon-db:latest
    build: ./docker/db
    ports:
      - 3306:3306
    volumes:
      - app-db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  app-tmp:
    driver: local
  app-db:
    driver: local
